[package]
name = "botto-chan"
version = "0.1.0"
authors = ["Marco Alka <me@marco-alka.de>"]

[dependencies]
discord = "0.8"
error-chain = "0.11"
ron = "0.1"
slog = "2"
slog-term = "2"
slog-async = "2"
unicode-segmentation = "1"
